### ISSUE TITLE
Does not build under 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux

### ISSUE THREAD

**Issue by kjonca** [koljah-de/e1000e-dkms-debian#2]
I tried to install it under my kernel and got:
error: implicit declaration of function ‘mmiowb’ 
full log in attachment.
[make.log](https://github.com/koljah-de/e1000e-dkms-debian/files/3634557/make.log)

**Comment by kjonca** [comment]
It seems that remove two calls of‘mmiowb’ resolves this problem.

**Comment by koljah-de** [comment]
I have tested the version 3.6.0. This works with Debian Bullseye (Testing) and Linux 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2. The bug should now be fixed.

This problem was also mentioned in the changelog for 3.6.0
