### ISSUE TITLE
Cannot compile with kernel 5.9

### ISSUE THREAD

**Issue by kjonca** [koljah-de/e1000e-dkms-debian#8]
After installing kernel 5.9.0-1-amd64 (x86_64)  package cannot build. log attached.

**Comment by kjonca** [comment]
[make.log](https://github.com/koljah-de/e1000e-dkms-debian/files/5398024/make.log)

**Comment by koljah-de** [comment]
Intel just released version 3.8.7. This works with Linux kernel 5.9.
